<?php require_once __DIR__ . '/componentes/componentes.php'; ?>
<!DOCTYPE html><html lang="pt-BR"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><link rel="stylesheet" href="../css/componentes.css"><link rel="stylesheet" href="../css/buscarPsicologos.css"><title>Mindly | Psicólogos</title></head><body><?php abrirLayout('paciente','psicologos','Encontre seu psicólogo','Conheça profissionais e escolha quem combina com você.','Ana Martins'); ?>
<div class="barra-busca cartao"><div class="busca"><?= icon('search') ?><input type="search" placeholder="Busque por nome ou área de atuação"></div><button class="botao botao-secundario"><?= icon('filter') ?> Filtros</button></div>
<div class="filtros-rapidos"><button class="filtro ativo">Todos</button><button class="filtro">Ansiedade</button><button class="filtro">Relacionamentos</button><button class="filtro">Autoconhecimento</button><button class="filtro">Estresse</button></div>
<div class="resultado-topo"><div><strong>Profissionais disponíveis</strong><span>24 psicólogos encontrados</span></div><select><option>Mais recomendados</option><option>Horário mais próximo</option></select></div>
<div class="grade-profissionais">
<article class="cartao profissional"><div class="topo-prof"><span class="avatar-foto grande">CS</span><button class="favorito"><?= icon('heart') ?></button></div><h2>Dra. Camila Souza</h2><p class="crp">CRP 06/123456</p><div class="avaliacao"><?= icon('star') ?><strong>4,9</strong><span>· 82 avaliações</span></div><div class="tags"><span class="tag">Ansiedade</span><span class="tag">Autoconhecimento</span></div><p class="descricao">Atendimento acolhedor com foco em adultos e jovens.</p><div class="rodape-prof"><div><small>Próximo horário</small><strong>Hoje, 16:30</strong></div><a class="botao botao-principal" href="perfilPsicologo.php">Ver perfil</a></div></article>
<article class="cartao profissional"><div class="topo-prof"><span class="avatar-foto grande">RL</span><button class="favorito"><?= icon('heart') ?></button></div><h2>Dr. Rafael Lima</h2><p class="crp">CRP 06/145820</p><div class="avaliacao"><?= icon('star') ?><strong>4,8</strong><span>· 67 avaliações</span></div><div class="tags"><span class="tag">Estresse</span><span class="tag">Relacionamentos</span></div><p class="descricao">Escuta atenta e acompanhamento personalizado para cada momento.</p><div class="rodape-prof"><div><small>Próximo horário</small><strong>Amanhã, 10:00</strong></div><a class="botao botao-principal" href="perfilPsicologo.php">Ver perfil</a></div></article>
<article class="cartao profissional"><div class="topo-prof"><span class="avatar-foto grande">MF</span><button class="favorito"><?= icon('heart') ?></button></div><h2>Dra. Marina Freitas</h2><p class="crp">CRP 06/167032</p><div class="avaliacao"><?= icon('star') ?><strong>5,0</strong><span>· 51 avaliações</span></div><div class="tags"><span class="tag">Autoconhecimento</span><span class="tag">Ansiedade</span></div><p class="descricao">Psicoterapia para construção de autonomia e bem-estar emocional.</p><div class="rodape-prof"><div><small>Próximo horário</small><strong>29 ago, 09:30</strong></div><a class="botao botao-principal" href="perfilPsicologo.php">Ver perfil</a></div></article>
</div><?php fecharLayout(); ?></body></html>