<?php require_once __DIR__ . '/../controller/Auth.php'; $currentUser = requireRole('psicologo'); ?>
<?php require_once __DIR__ . '/../controller/DadosController.php'; $d=loadPageData(basename(__FILE__),$currentUser);
require_once __DIR__ . '/componentes/componentes.php'; require_once __DIR__ . '/componentes/dados.php'; ?>
<!DOCTYPE html><html lang="pt-BR"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><link rel="stylesheet" href="../css/componentes.css"><link rel="stylesheet" href="../css/prontuarioPsicologo.css"><title>Mindly | Prontuários</title></head><body><?php abrirLayout('psicologo','prontuarios','Prontuário digital','Registre e acompanhe informações dos atendimentos.',$currentUser['nome']); ?>
<div class="pront-grid"><aside class="cartao lista-pacientes"><div class="busca"><?= icon('users') ?><strong>Pacientes vinculados</strong></div><?php foreach($d['pacientes'] as $p): ?><a class="paciente-item <?= ($d['paciente']['id'] ?? null)===$p['id']?'ativo':'' ?>" href="<?= e(publicLink('prontuarioPsicologo.php',$p['id'],'paciente_id')) ?>"><span class="avatar-foto"><?= e(initials($p['nome'])) ?></span><div><strong><?= e($p['nome']) ?></strong><small><?= (int)$p['sessoes'] ?> sessões</small></div></a><?php endforeach; if(!$d['pacientes'])emptyState('Nenhum paciente vinculado até o momento.'); ?></aside><section class="cartao prontuario"><div class="cabecalho-paciente"><div class="ident"><span class="avatar-foto grande"><?= e(initials($d['paciente']['nome'] ?? '')) ?></span><div><h2><?= e($d['paciente']['nome'] ?? 'Selecione um paciente') ?></h2><span>Observações privadas acessíveis somente ao profissional responsável</span></div></div></div>
<?php if($p=$d['paciente']): ?><div class="metricas"><div><span>Sessões realizadas</span><strong><?= (int)$p['sessoes'] ?></strong></div><div><span>Último atendimento</span><strong><?= dateLabel($d['contextoClinico'][0]['inicio_em'] ?? null,'d/m/Y') ?></strong></div><div><span>Próxima consulta</span><strong><?= dateLabel($p['proxima']) ?></strong></div></div><a href="<?= e(publicLink('pacientesPsicologo.php',$p['id'],'paciente_id')) ?>">Histórico completo do acompanhamento</a><?php endif; ?>
<?php foreach($d['contextoClinico'] as $context): ?><article class="registro-atual"><div class="registro-topo"><div><span><?= dateLabel($context['inicio_em']) ?> · Consulta #<?= (int)$context['id'] ?></span><h3><?= $context['registro_id']?'Editar registro':'Novo registro de atendimento' ?></h3></div></div><form class="form-operacao" method="post" action="../processamento/profissional.php"><?php operationFields('registro'); ?><input type="hidden" name="consulta_id" value="<?= (int)$context['id'] ?>"><input type="hidden" name="paciente_id" value="<?= (int)$context['paciente_id'] ?>"><input type="hidden" name="versao" value="<?= hash('sha256',$context['observacoes'] ?? '') ?>"><label class="campo">Observações clínicas privadas<textarea name="observacoes" maxlength="20000" required><?= e($context['observacoes'] ?? '') ?></textarea></label><div class="registro-rodape"><span><?= icon('shield') ?> Não será compartilhado com o paciente</span><button class="botao botao-principal">Salvar registro privado</button></div></form><?php if($context['registro_id']): ?><small>Criado em <?= dateLabel($context['criado_em']) ?> · Atualizado em <?= dateLabel($context['atualizado_em']) ?></small><details><summary>Versões anteriores da anotação</summary><?php $found=false;foreach($d['versoes'] as $v):if((int)$v['registro_id']!==(int)$context['registro_id'])continue;$found=true; ?><article><small>Preservada em <?= dateLabel($v['salvo_em']) ?></small><p class="texto-clinico"><?= nl2br(e($v['observacoes'])) ?></p></article><?php endforeach;if(!$found)emptyState('Nenhuma edição anterior.'); ?></details><?php endif; ?>
<details><summary>Resumo para o paciente (compartilhamento explícito)</summary><form class="form-operacao" method="post" action="../processamento/profissional.php"><?php operationFields('resumo'); ?><input type="hidden" name="consulta_id" value="<?= (int)$context['id'] ?>"><input type="hidden" name="paciente_id" value="<?= (int)$context['paciente_id'] ?>"><input type="hidden" name="versao" value="<?= hash('sha256',$context['resumo'] ?? '') ?>"><label>Resumo<textarea name="resumo" maxlength="10000" required><?= e($context['resumo'] ?? '') ?></textarea></label><label><input type="checkbox" name="compartilhar" value="1" required> Confirmo que este resumo pode ser visualizado pelo paciente.</label><button class="botao botao-suave">Salvar e compartilhar resumo</button></form><small>Último compartilhamento: <?= dateLabel($context['compartilhado_em']) ?></small></details></article><?php endforeach;if(!$d['contextoClinico'])emptyState('Nenhum atendimento concluído disponível para registro.'); ?></section></div>
<?php fecharLayout(); ?></body></html>
